language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install tox depdendency, which then knows how to install any other dependencies
install: "pip install tox"
# command to run tests
script: tox
